export const comments = [
  {
    nickname: '부우부',
    time: '2022.12.03 11:44',
    content: '부우부부우부부우부부우부부우부부우부부우부',
    id: 1,
    likeState: true,
    likesCount: 5,
    questionId: 1,
    userId: 1,
  },
  {
    nickname: '부우부',
    time: '2022.12.03 11:44',
    content: '부우부부우부부우부부우부부우부부우부부우부',
    id: 2,
    likeState: true,
    likesCount: 5,
    questionId: 1,
    userId: 2,
  },
  {
    nickname: '부우부',
    time: '2022.12.03 11:44',
    content: '부우부부우부부우부부우부부우부부우부부우부',
    id: 3,
    likeState: true,
    likesCount: 5,
    questionId: 1,
    userId: 1,
  },
  {
    nickname: '부우부',
    time: '2022.12.03 11:44',
    content: '부우부부우부부우부부우부부우부부우부부우부',
    id: 4,
    likeState: true,
    likesCount: 5,
    questionId: 1,
    userId: 1,
  },
];
