import { PostCategory } from './../../types';
export const categorys = [
  { label: '자유게시판', path: '/community', query: { c: PostCategory.Free } },
  { label: '시험후기', path: '/community', query: { c: PostCategory.Review } },
  { label: '공지사항', path: '/community', query: { c: PostCategory.Notice } },
];

export const mockPosts = [
  {
    title: '안녕하세요',
    category: '자유게시판',
    userName: '부우',
    date: '2021.12.03',
    viewCount: 5,
    likeCount: 4,
    commentCount: 10,
    id: 1,
  },
  {
    title: '안녕하세요',
    category: '자유게시판',
    userName: '부우',
    date: '2021.12.03',
    viewCount: 5,
    likeCount: 4,
    commentCount: 10,
    id: 2,
  },
  {
    title: '안녕하세요',
    category: '자유게시판',
    userName: '부우',
    date: '2021.12.03',
    viewCount: 5,
    likeCount: 4,
    commentCount: 10,
    id: 3,
  },
  {
    title: '안녕하세요',
    category: '자유게시판',
    userName: '부우',
    date: '2021.12.03',
    viewCount: 5,
    likeCount: 4,
    commentCount: 10,
    id: 4,
  },
  {
    title: '안녕하세요',
    category: '자유게시판',
    userName: '부우',
    date: '2021.12.03',
    viewCount: 5,
    likeCount: 4,
    commentCount: 10,
    id: 5,
  },
  {
    title: '안녕하세요',
    category: '자유게시판',
    userName: '부우',
    date: '2021.12.03',
    viewCount: 5,
    likeCount: 4,
    commentCount: 10,
    id: 6,
  },
  {
    title: '안녕하세요',
    category: '자유게시판',
    userName: '부우',
    date: '2021.12.03',
    viewCount: 5,
    likeCount: 4,
    commentCount: 10,
    id: 7,
  },
  {
    title: '안녕하세요',
    category: '자유게시판',
    userName: '부우',
    date: '2021.12.03',
    viewCount: 5,
    likeCount: 4,
    commentCount: 10,
    id: 8,
  },
  {
    title: '안녕하세요',
    category: '자유게시판',
    userName: '부우',
    date: '2021.12.03',
    viewCount: 5,
    likeCount: 4,
    commentCount: 10,
    id: 9,
  },
  {
    title: '안녕하세요',
    category: '자유게시판',
    userName: '부우',
    date: '2021.12.03',
    viewCount: 5,
    likeCount: 4,
    commentCount: 10,
    id: 10,
  },
  {
    title: '안녕하세요',
    category: '자유게시판',
    userName: '부우',
    date: '2021.12.03',
    viewCount: 5,
    likeCount: 4,
    commentCount: 10,
    id: 11,
  },
];
