export const EXAM_SOLUTION_PAGE = 'EXAM_SOLUTION_PAGE';
export const EXAM_PDF_PAGE = 'EXAM_PDF_PAGE';
export const STUDY_PAGE = 'STUDY_PAGE';
export const EXAM_CREATE_PAGE = 'EXAM_CREATE_PAGE';
export const PRICING_PAGE = 'PRICING_PAGE';
export const MAIN_PAGE = 'MAIN_PAGE';
export const QUESTION_PAGE = 'QUESTION_PAGE';
export const QUESTION_EDIT_PAGE = 'QUESTION_EDIT_PAGE';
