export const IN_PROGRESS_ANSWERS = 'IN_PROGRESS_ANSWERS';

export const LAST_VISITED_CATEGORY = 'LAST_VISITED_CATEGORY';

export const LAST_VISITED_CATEGORY_ID = 'LAST_VISITED_CATEGORY_ID';

export const BOOKMARK_FOLDER_ID = 'BOOKMARK_FOLDER_ID';

export const HIGHLIGHTS = 'HIGHLIGHTS';
