export const IS_FIRST_VISIT = 'IS_FIRST_VISIT';
export const CURRENT_QUESTION_INDEX_LIST = 'CURRENT_QUESTION_INDEX_LIST';
export const PUBLIC_EXAM_ID = 'PUBLIC_EXAM_ID';
export const PUBLIC_CATEGORY_ID = 'PUBLIC_CATEGORY_ID';
